export const FETCH_INPUT_OPTIONS_REQUEST = 'FETCH_INPUT_OPTIONS_REQUEST'
export const FETCH_INPUT_OPTIONS_FAILURE = 'FETCH_INPUT_OPTIONS_FAILURE'
export const FETCH_INPUT_OPTIONS_SUCCESS = 'FETCH_INPUT_OPTIONS_SUCCESS'
